-- =========================================================
-- Training Management Module — actual MySQL schema
-- Generated from the live database after synchronization.
-- Runtime migrations live in backend/models/trainingTables.js
-- =========================================================

CREATE TABLE `training_employees` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `training_id` varchar(20) NOT NULL,
  `employee_code` varchar(20) DEFAULT NULL,
  `first_name` varchar(100) NOT NULL,
  `middle_name` varchar(100) DEFAULT NULL,
  `last_name` varchar(100) DEFAULT NULL,
  `full_name` varchar(255) DEFAULT NULL,
  `father_name` varchar(255) DEFAULT NULL,
  `father_aadhaar` varchar(20) DEFAULT NULL,
  `mother_name` varchar(255) DEFAULT NULL,
  `mother_aadhaar` varchar(20) DEFAULT NULL,
  `spouse_name` varchar(255) DEFAULT NULL,
  `spouse_aadhaar` varchar(20) DEFAULT NULL,
  `gender` enum('Male','Female','Other') DEFAULT NULL,
  `dob` date DEFAULT NULL,
  `marital_status` varchar(50) DEFAULT NULL,
  `blood_group` varchar(20) DEFAULT NULL,
  `mobile` varchar(15) NOT NULL,
  `alternate_mobile` varchar(15) DEFAULT NULL,
  `email` varchar(150) DEFAULT NULL,
  `emergency_contact1_name` varchar(255) DEFAULT NULL,
  `emergency_contact1_relation` varchar(100) DEFAULT NULL,
  `emergency_contact1_mobile` varchar(15) DEFAULT NULL,
  `emergency_contact2_name` varchar(255) DEFAULT NULL,
  `emergency_contact2_relation` varchar(100) DEFAULT NULL,
  `emergency_contact2_mobile` varchar(15) DEFAULT NULL,
  `aadhaar_no` varchar(20) NOT NULL,
  `pan_no` varchar(20) DEFAULT NULL,
  `imei_number` varchar(50) DEFAULT NULL,
  `nominee_name` varchar(255) DEFAULT NULL,
  `nominee_relation` varchar(100) DEFAULT NULL,
  `nominee_mobile` varchar(15) DEFAULT NULL,
  `pf_uan_available` enum('Yes','No') DEFAULT NULL,
  `pf_uan_number` varchar(100) DEFAULT NULL,
  `esic_available` enum('Yes','No') DEFAULT NULL,
  `esic_number` varchar(100) DEFAULT NULL,
  `voter_id` varchar(30) DEFAULT NULL,
  `driving_license` varchar(50) DEFAULT NULL,
  `passport_no` varchar(50) DEFAULT NULL,
  `current_address` text DEFAULT NULL,
  `current_pincode` varchar(10) DEFAULT NULL,
  `aadhaar_address` text DEFAULT NULL,
  `aadhaar_pincode` varchar(10) DEFAULT NULL,
  `address` text DEFAULT NULL,
  `city` varchar(100) DEFAULT NULL,
  `district` varchar(100) DEFAULT NULL,
  `state` varchar(100) DEFAULT NULL,
  `pincode` varchar(10) DEFAULT NULL,
  `qualification` varchar(150) DEFAULT NULL,
  `specialization` varchar(150) DEFAULT NULL,
  `passing_year` varchar(10) DEFAULT NULL,
  `institute_name` varchar(255) DEFAULT NULL,
  `institute_state` varchar(100) DEFAULT NULL,
  `experience_years` decimal(4,1) DEFAULT NULL,
  `previous_company` varchar(255) DEFAULT NULL,
  `designation` varchar(150) DEFAULT NULL,
  `position_applied` varchar(150) DEFAULT NULL,
  `employee_vendor_code` varchar(100) DEFAULT NULL,
  `department` varchar(100) DEFAULT NULL,
  `circle` varchar(100) DEFAULT NULL,
  `cmp` varchar(150) DEFAULT NULL,
  `project` varchar(150) DEFAULT NULL,
  `reporting_manager` varchar(150) DEFAULT NULL,
  `training_location` varchar(150) DEFAULT NULL,
  `joining_date` date DEFAULT NULL,
  `bank_name` varchar(150) DEFAULT NULL,
  `account_number` varchar(50) DEFAULT NULL,
  `ifsc_code` varchar(20) DEFAULT NULL,
  `branch_name` varchar(150) DEFAULT NULL,
  `account_holder_name` varchar(150) DEFAULT NULL,
  `training_status` enum('Pending','Under Review','Approved','Rejected','Converted') DEFAULT 'Pending',
  `employee_status` enum('Active','Inactive') DEFAULT 'Active',
  `remarks` text DEFAULT NULL,
  `google_form_response_id` varchar(100) DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `form_response_id` varchar(191) DEFAULT NULL,
  `converted_at` datetime DEFAULT NULL,
  `converted_by` varchar(150) DEFAULT NULL,
  `training_batch` varchar(120) DEFAULT NULL,
  `training_start_date` date DEFAULT NULL,
  `training_end_date` date DEFAULT NULL,
  `source` enum('google_form','manual') NOT NULL DEFAULT 'google_form',
  PRIMARY KEY (`id`),
  UNIQUE KEY `training_id` (`training_id`),
  UNIQUE KEY `aadhaar_no` (`aadhaar_no`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `training_documents` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `training_employee_id` int(11) NOT NULL,
  `document_type` enum('Photo','Resume','Aadhaar Front','Aadhaar Back','PAN','Passbook','Driving License','Police Verification','Medical Certificate','Education Certificate','Experience Letter','Other') NOT NULL,
  `file_name` varchar(255) DEFAULT NULL,
  `file_url` text DEFAULT NULL,
  `google_drive_file_id` varchar(255) DEFAULT NULL,
  `uploaded_at` timestamp NULL DEFAULT current_timestamp(),
  `local_path` varchar(500) DEFAULT NULL,
  `drive_file_id` varchar(191) DEFAULT NULL,
  `mime_type` varchar(120) DEFAULT NULL,
  `file_size` bigint(20) DEFAULT NULL,
  `verification_status` enum('Pending','Verified','Rejected') NOT NULL DEFAULT 'Pending',
  `verified_by` varchar(150) DEFAULT NULL,
  `verified_at` datetime DEFAULT NULL,
  `remarks` text DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `training_employee_id` (`training_employee_id`),
  CONSTRAINT `training_documents_ibfk_1` FOREIGN KEY (`training_employee_id`) REFERENCES `training_employees` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `training_verifications` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `training_employee_id` int(11) NOT NULL,
  `aadhaar_verified` tinyint(1) DEFAULT 0,
  `pan_verified` tinyint(1) DEFAULT 0,
  `bank_verified` tinyint(1) DEFAULT 0,
  `police_verified` tinyint(1) DEFAULT 0,
  `medical_verified` tinyint(1) DEFAULT 0,
  `documents_verified` tinyint(1) DEFAULT 0,
  `verified_by` varchar(150) DEFAULT NULL,
  `verified_at` datetime DEFAULT NULL,
  `verification_status` enum('Pending','Verified','Rejected') DEFAULT 'Pending',
  `remarks` text DEFAULT NULL,
  `document_id` int(11) DEFAULT NULL,
  `action` varchar(50) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `training_employee_id` (`training_employee_id`),
  CONSTRAINT `training_verifications_ibfk_1` FOREIGN KEY (`training_employee_id`) REFERENCES `training_employees` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `training_logs` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `training_employee_id` int(11) DEFAULT NULL,
  `action` varchar(150) DEFAULT NULL,
  `action_by` int(11) DEFAULT NULL,
  `action_details` text DEFAULT NULL,
  `ip_address` varchar(100) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `performed_by` varchar(150) DEFAULT 'system',
  PRIMARY KEY (`id`),
  KEY `training_employee_id` (`training_employee_id`),
  CONSTRAINT `training_logs_ibfk_1` FOREIGN KEY (`training_employee_id`) REFERENCES `training_employees` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

